var i18n = {
  'P_MultiAge_Aviary': 'Aviary',
  'P_MultiAge_CarnivalBonus17': 'Masquerade Ball',
  'R_MultiAge_CarnivalBonus17': 'Renaissance Mansion',
  'P_MultiAge_CarnivalBonus18': 'Gondola Dock Market',
  'R_MultiAge_CarnivalBonus18a': 'Grand Bridge',
  'R_MultiAge_CarnivalBonus18b': 'Grand Bridge (lvl 2)',
  'R_MultiAge_CarnivalBonus18c': 'Grand Bridge (lvl 3)',
  'R_MultiAge_ChristmasBonus1': 'Log Cabin',
  'P_MultiAge_ChristmasBonus1': 'Confectionary',
  'P_MultiAge_ChristmasBonus2': 'Large Confectionary',
  'R_MultiAge_ChristmasBonus3': 'Gingerbread House',
  'P_MultiAge_ChristmasBonus16': "Santa's Workshop",
  'P_MultiAge_CupBonus16': 'Soccer Field',
  'P_MultiAge_EasterBonus16': 'Foeberge Shop',
  'R_MultiAge_EasterBonus16': 'Shrine of Inspiration',
  'P_MultiAge_Expedition16': 'Terrace Farm',
  'P_MultiAge_FallBonus16': 'Cider Mill',
  'P_MultiAge_FallBonus17a': 'Blooming Cider Mill',
  'P_MultiAge_FallBonus17b': 'Fruitful Cider Mill',
  'P_MultiAge_FallBonus17c': 'Bountiful Cider Mill',
  'R_MultiAge_FallBonus18': 'Forest of Fall',
  'R_MultiAge_FallBonus18b': 'Mill of Fall',
  'P_MultiAge_HalloweenBonus15': "Mad Scientist's Lab",
  'P_MultiAge_MonroeBonus17': 'Rosarium',
  'R_MultiAge_NapoleonBonus18': 'Royal Marble Gateway',
  'R_BronzeAge_Residential4': 'Longhouse',
  'R_LateMiddleAge_Residential3': 'Kasteel',
  'R_MultiAge_RoyalBonusSet17a': 'King Statue',
  'R_MultiAge_RoyalBonusSet17b': 'Queens Statue',
  'P_MultiAge_SportBonus17': 'Arena of Victors',
  'R_MultiAge_SportBonus17c': 'Pillar of Heroes',
  'R_MultiAge_SportBonus18b': 'Tholos of Idols (lvl 2)',
  'R_MultiAge_SportBonus18c': 'Tholos of Idols (lvl 3)',
  'R_MultiAge_SpringBonus17a': 'One-Story Pagoda',
  'L_AllAge_SpringBonusSet17': 'Gong of Wisdom',
  'R_MultiAge_SpringBonusSet17a': 'Zen Zone',
  'R_MultiAge_SpringBonusSet17b': "Emperor's Entrance",
  'L_AllAge_SpringBonusSet18': 'Gong of Wisdom (lvl 2)',
  'R_MultiAge_SpringBonusSet18a': 'Zen Zone (lvl2)',
  'R_MultiAge_SpringBonusSet18b': "Emperor's Entrance (lvl2)",
  'R_MultiAge_SummerBonus15': 'Ziggurat',
  'R_MultiAge_SummerBonusSetA17a': "Maharaja's Palace",
  'R_MultiAge_SummerBonusSetA17b': 'Western Palace Tower',
  'R_MultiAge_SummerBonusSetA17c': 'Eastern Palace Tower',
  'R_MultiAge_SummerBonusSetB17a': 'Memorial Chhatri',
  'R_MultiAge_SummerBonusSetB17b': 'Elephant Fountain Gate',
  'P_MultiAge_SummerBonus15': 'Bazaar',
  'P_MultiAge_SummerBonus16': 'Luau',
  'P_MultiAge_SummerBonus18': 'Sunken Treasure',
  'P_MultiAge_VanGoghBonus18': 'Magnum Opus',
  'P_HighMiddleAge_Windmill': 'Windmill',
  'R_MultiAge_WinterBonusSet17a': "Sugar Baker's Booth",
  'R_MultiAge_WinterBonusSet17b': 'Moose Meadow',
  'R_MultiAge_WinterBonusSet17c': "Toymaker's Booth"
};
