'use strict'

const i18n = {
  'R_MultiAge_ArcheologyBonus19a': "World's Fair",
  'P_MultiAge_Aviary': 'Aviary',
  'R_MultiAge_BirthdayBonus1': 'The King',
  'P_MultiAge_CarnivalBonus17': 'Masquerade Ball',
  'R_MultiAge_CarnivalBonus17': 'Renaissance Mansion',
  'P_MultiAge_CarnivalBonus18': 'Gondola Dock Market',
  'R_MultiAge_CarnivalBonus18': 'Renaissance Mansion',
  'R_MultiAge_CarnivalBonus18a': 'Grand Bridge',
  'R_MultiAge_CarnivalBonus18b': 'Grand Bridge (lvl 2)',
  'R_MultiAge_CarnivalBonus18c': 'Grand Bridge (lvl 3)',
  'R_MultiAge_CarnivalBonus19d': 'Piazza Cafe (lvl 2)',
  'R_MultiAge_CarnivalBonus19a': 'Piazza Homes',
  'R_MultiAge_CarnivalBonus19b': 'Piazza Homes (lvl 2)',
  'R_MultiAge_CarnivalBonus19c': 'Piazza Cafe',
  'R_MultiAge_ChristmasBonus1': 'Log Cabin',
  'P_MultiAge_ChristmasBonus1': 'Confectionary',
  'P_MultiAge_ChristmasBonus2': 'Large Confectionary',
  'R_MultiAge_ChristmasBonus3': 'Gingerbread House',
  'P_MultiAge_ChristmasBonus16': "Santa's Workshop",
  'P_MultiAge_CupBonus16': 'Soccer Field',
  'P_MultiAge_EasterBonus16': 'Foeberge Shop',
  'R_MultiAge_EasterBonus16': 'Shrine of Inspiration',
  'R_MultiAge_EinsteinBonus17': 'Checkmate Square',
  'P_MultiAge_Expedition16': 'Terrace Farm',
  'P_MultiAge_FallBonus16': 'Cider Mill',
  'P_MultiAge_FallBonus17a': 'Blooming Cider Mill',
  'P_MultiAge_FallBonus17b': 'Fruitful Cider Mill',
  'P_MultiAge_FallBonus17c': 'Bountiful Cider Mill',
  'P_MultiAge_FallBonus17d': 'Prosperous Cider Mill',
  'R_MultiAge_FallBonus18': 'Forest of Fall',
  'R_MultiAge_FallBonus18b': 'Mill of Fall',
  'G_IndustrialAge_GoodProduction1': 'Rubber Plant',
  'G_IndustrialAge_GoodProduction2': 'Coke Oven',
  'G_IndustrialAge_GoodProduction3': 'Textile Mill',
  'G_IndustrialAge_GoodProduction4': 'Whaling Station',
  'G_IndustrialAge_GoodProduction5': 'Fertilizer Plant',
  'G_ProgressiveEra_GoodProduction1': 'Asbestos Factory',
  'G_ProgressiveEra_GoodProduction2': 'Oil Refinery',
  'G_ProgressiveEra_GoodProduction3': 'Machine Workshop',
  'G_ProgressiveEra_GoodProduction4': 'Tinning Plant',
  'G_ProgressiveEra_GoodProduction5': 'Explosives Factory',
  'R_MultiAge_HalloweenBonus4': 'Haunted House',
  'P_MultiAge_HalloweenBonus15': "Mad Scientist's Lab",
  'P_MultiAge_MonroeBonus17': 'Rosarium',
  'R_MultiAge_NapoleonBonus18': 'Royal Marble Gateway',
  'R_BronzeAge_Residential4': 'Longhouse',
  'R_LateMiddleAge_Residential3': 'Kasteel',
  'R_MultiAge_RoyalBonusSet17a': 'King Statue',
  'R_MultiAge_RoyalBonusSet17b': 'Queens Statue',
  'R_MultiAge_SoccerBonus19a': 'Altar Garden',
  'R_MultiAge_SoccerBonus19b': 'Altar Garden (lvl 2)',
  'R_MultiAge_SoccerBonus19c': 'Altar Garden (lvl 3)',
  'R_MultiAge_SoccerBonus19d': 'Altar Garden (lvl 4)',
  'P_MultiAge_SportBonus17': 'Arena of Victors',
  'R_MultiAge_SportBonus17c': 'Pillar of Heroes',
  'R_MultiAge_SportBonus18a': 'Tholos of Idols',
  'R_MultiAge_SportBonus18b': 'Tholos of Idols (lvl 2)',
  'R_MultiAge_SportBonus18c': 'Tholos of Idols (lvl 3)',
  'R_MultiAge_SportBonusSet18': 'Classical Garden Patio',
  'R_MultiAge_SpringBonus17a': 'Pagoda',
  'R_MultiAge_SpringBonus17b': 'Pagoda (lvl 2)',
  'L_AllAge_SpringBonusSet17': 'Gong of Wisdom',
  'R_MultiAge_SpringBonusSet17a': 'Zen Zone',
  'R_MultiAge_SpringBonusSet17b': "Emperor's Entrance",
  'L_AllAge_SpringBonusSet18': 'Gong of Wisdom (lvl 2)',
  'R_MultiAge_SpringBonusSet18a': 'Zen Zone (lvl 2)',
  'R_MultiAge_SpringBonusSet18b': "Emperor's Entrance (lvl 2)",
  'R_MultiAge_SummerBonus2': 'Oase',
  'R_MultiAge_SummerBonus15': 'Ziggurat',
  'P_MultiAge_SummerBonus15': 'Bazaar',
  'P_MultiAge_SummerBonus16': 'Luau',
  'P_MultiAge_SummerBonus18': 'Sunken Treasure',
  'R_MultiAge_SummerBonus18a': 'The Ship (lvl 1)',
  'R_MultiAge_SummerBonus18b': 'The Ship (lvl 2)',
  'R_MultiAge_SummerBonus18c': 'The Ship (lvl 3)',
  'R_MultiAge_SummerBonus18d': 'The Ship (lvl 4)',
  'R_MultiAge_SummerBonus18e': 'The Ship (lvl 5)',
  'R_MultiAge_SummerBonus18f': 'The Ship (lvl 6)',
  'R_MultiAge_SummerBonusSetA17a': "Maharaja's Palace",
  'R_MultiAge_SummerBonusSetA17b': 'Western Palace Tower',
  'R_MultiAge_SummerBonusSetA17c': 'Eastern Palace Tower',
  'R_MultiAge_SummerBonusSetB17a': 'Memorial Chhatri',
  'R_MultiAge_SummerBonusSetB17b': 'Elephant Fountain Gate',
  'P_MultiAge_VanGoghBonus18': 'Magnum Opus',
  'P_HighMiddleAge_Windmill': 'Windmill',
  'R_MultiAge_WinterBonus18': 'Charming Cottage',
  'R_MultiAge_WinterBonus18b': 'Winter Spire (lvl 2)',
  'R_MultiAge_WinterBonusSet17a': "Sugar Baker's Booth",
  'R_MultiAge_WinterBonusSet17b': 'Moose Meadow',
  'R_MultiAge_WinterBonusSet17c': "Toymaker's Booth",
  'P_MultiAge_WinterBonus18': 'Sleigh Builder',
  'P_ProgressiveEra_Workshop1': 'Cattle Ranch',
  'P_IndustrialAge_Workshop2': 'Ceramics Factory'
}
