var i18n = {
  'P_MultiAge_Aviary': 'Aviary',
  'P_MultiAge_CarnivalBonus17': 'Masquerade Ball',
  'P_MultiAge_CarnivalBonus18': 'Gondola Dock Market',
  'R_MultiAge_CarnivalBonus18c': '? Grand Bridge ?',
  'P_MultiAge_ChristmasBonus16': "Santa's Workshop",
  'P_MultiAge_Expedition16': '??? (P_MultiAge_Expedition16)',
  'P_MultiAge_FallBonus17a': 'Blooming Cider Mill',
  'P_MultiAge_FallBonus17b': 'Fruitful Cider Mill',
  'P_MultiAge_FallBonus17c': 'Bountiful Cider Mill',
  'P_MultiAge_HalloweenBonus15': "Mad Scientist's Lab",
  'R_MultiAge_NapoleonBonus18': 'Royal Marble Gateway',
  'R_LateMiddleAge_Residential3': 'Kasteel',
  'R_MultiAge_RoyalBonusSet17a': 'King Statue',
  'R_MultiAge_RoyalBonusSet17b': 'Queens Statue',
  'P_MultiAge_SportBonus17': 'Arena of Victors',
  'L_AllAge_SpringBonusSet17': '? Gong of Wisdom ?',
  'R_MultiAge_SpringBonusSet17a': 'Zen Zone',
  'R_MultiAge_SpringBonusSet17b': "Emperor's Entrance",
  'R_MultiAge_SpringBonusSet18a': 'Zen Zone (lvl2)',
  'R_MultiAge_SpringBonusSet18b': "Emperor's Entrance (lvl2)",
  'R_MultiAge_SummerBonusSetA17a': "Maharaja's Palace",
  'R_MultiAge_SummerBonusSetA17b': '? Western Palace Tower ?',
  'R_MultiAge_SummerBonusSetA17c': '? Eastern Palace Tower ?',
  'R_MultiAge_SummerBonusSetB17b': 'Elephant Fountain Gate',
  'P_MultiAge_SummerBonus15': 'Bazaar',
  'P_MultiAge_SummerBonus16': 'Luau',
  'P_MultiAge_SummerBonus18': 'Sunken Treasure'
};
